AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 125

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

StringLiterals:
  EnforcedStyle: double_quotes

DotPosition:
  EnforcedStyle: leading
